[project]
name = "smart-home-control-panel"
version = "0.1.0"
description = ""
authors = [
    {name = "Soumya2024",email = "habra4561@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "tk-tools (>=0.17.0,<0.18.0)",
    "paho-mqtt (>=2.1.0,<3.0.0)",
    "pyinstaller (>=6.13.0,<7.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "tk (>=0.1.0,<0.2.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
